# Generated by Django 3.0.5 on 2021-05-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_model',
            name='advisor_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
