# Generated by Django 3.0.5 on 2021-05-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210513_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_models',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
