# Generated by Django 3.0.5 on 2021-05-13 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20210513_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_book_call',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
