# Generated by Django 3.0.5 on 2021-05-13 13:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20210513_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_book_call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advisor_name', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('advisor_id', models.IntegerField()),
                ('booking_id', models.IntegerField()),
                ('advisor_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_models', to='pages.admin_model')),
            ],
        ),
    ]
