# Generated by Django 3.0.5 on 2021-05-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_all_book_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_book_call',
            name='advisor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.admin_model'),
        ),
    ]
