# Generated by Django 3.0.5 on 2021-05-13 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_auto_20210513_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_book_call',
            name='booking_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.can_book_call'),
        ),
    ]
