# Generated by Django 3.0.5 on 2021-05-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210513_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_book_call',
            name='advisor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_model', to='pages.admin_model'),
        ),
        migrations.AlterField(
            model_name='all_book_call',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='can_book_call', to='pages.can_book_call'),
        ),
    ]
