# Generated by Django 3.0.5 on 2021-05-13 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_auto_20210513_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_book_call',
            name='advisor_id',
        ),
        migrations.RemoveField(
            model_name='all_book_call',
            name='advisor_image',
        ),
        migrations.RemoveField(
            model_name='all_book_call',
            name='booking_id',
        ),
        migrations.RemoveField(
            model_name='all_book_call',
            name='date',
        ),
        migrations.AlterField(
            model_name='all_book_call',
            name='advisor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.admin_model'),
        ),
    ]
