# Generated by Django 3.0.5 on 2021-05-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_auto_20210513_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='can_book_call',
            name='booking_id',
            field=models.CharField(max_length=100),
        ),
    ]
